package org.jboss.html5.model;
// Generated 25-Sep-2016 11:42:16 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Manufacturer generated by hbm2java
 */
@Entity
@Table(name = "manufacturer", catalog = "4fashion")
public class Manufacturer implements Serializable {
	private static final long serialVersionUID = 7033626119079406575L;
	
	private long manufacturerId;
	private String companyName;
	private String fantasyName;
	private Set<ProductManufacturer> productManufacturers = new HashSet<ProductManufacturer>(0);

	public Manufacturer() {
	}

	public Manufacturer(long manufacturerId) {
		this.manufacturerId = manufacturerId;
	}

	public Manufacturer(long manufacturerId, String companyName, String fantasyName,
			Set<ProductManufacturer> productManufacturers) {
		this.manufacturerId = manufacturerId;
		this.companyName = companyName;
		this.fantasyName = fantasyName;
		this.productManufacturers = productManufacturers;
	}

	@Id
	@Column(name = "MANUFACTURER_ID", unique = true, nullable = false)
	public long getManufacturerId() {
		return this.manufacturerId;
	}

	public void setManufacturerId(long manufacturerId) {
		this.manufacturerId = manufacturerId;
	}

	@Column(name = "COMPANY_NAME", length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "FANTASY_NAME", length = 45)
	public String getFantasyName() {
		return this.fantasyName;
	}

	public void setFantasyName(String fantasyName) {
		this.fantasyName = fantasyName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "manufacturer")
	public Set<ProductManufacturer> getProductManufacturers() {
		return this.productManufacturers;
	}

	public void setProductManufacturers(Set<ProductManufacturer> productManufacturers) {
		this.productManufacturers = productManufacturers;
	}

}
