package org.jboss.html5.model;
// Generated 25-Sep-2016 11:42:16 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "4fashion")
public class Payment implements Serializable {
	private static final long serialVersionUID = -1487188784896494660L;
	
	private long paymentId;
	private Order order;
	private Paymode paymode;

	public Payment() {
	}

	public Payment(long paymentId, Order order, Paymode paymode) {
		this.paymentId = paymentId;
		this.order = order;
		this.paymode = paymode;
	}

	@Id
	@Column(name = "PAYMENT_ID", unique = true, nullable = false)
	public long getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(long paymentId) {
		this.paymentId = paymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_FK", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAYMODE_FK", nullable = false)
	public Paymode getPaymode() {
		return this.paymode;
	}

	public void setPaymode(Paymode paymode) {
		this.paymode = paymode;
	}

}
