package org.jboss.html5.model;
// Generated 25-Sep-2016 11:42:16 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Paymode generated by hbm2java
 */
@Entity
@Table(name = "paymode", catalog = "4fashion")
public class Paymode implements Serializable {
	private static final long serialVersionUID = -3354762507550584716L;
	
	private long paymodeId;
	private String description;
	private Set<Payment> payments = new HashSet<Payment>(0);

	public Paymode() {
	}

	public Paymode(long paymodeId) {
		this.paymodeId = paymodeId;
	}

	public Paymode(long paymodeId, String description, Set<Payment> payments) {
		this.paymodeId = paymodeId;
		this.description = description;
		this.payments = payments;
	}

	@Id
	@Column(name = "PAYMODE_ID", unique = true, nullable = false)
	public long getPaymodeId() {
		return this.paymodeId;
	}

	public void setPaymodeId(long paymodeId) {
		this.paymodeId = paymodeId;
	}

	@Column(name = "DESCRIPTION", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymode")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
