package org.jboss.html5.model;
// Generated 25-Sep-2016 11:42:16 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "4fashion")
public class Person implements Serializable {
	private static final long serialVersionUID = -4247631972910028965L;
	
	private long personId;
	private String fullname;
	private String identificationNumber;
	private String individualCode;
	private Date birthDate;
	private String postalCode;
	private String federalState;
	private String city;
	private String district;
	private String location;
	private String country;
	private String addressComplement;
	private String cellPhone;
	private String phone;
	private String maritalStatus;
	private Set<Buyer> buyers = new HashSet<Buyer>(0);
	private Set<Vendor> vendors = new HashSet<Vendor>(0);

	public Person() {
	}

	public Person(long personId, String fullname) {
		this.personId = personId;
		this.fullname = fullname;
	}

	public Person(long personId, String fullname, String identificationNumber, String individualCode, Date birthDate,
			String postalCode, String federalState, String city, String district, String location, String country,
			String addressComplement, String cellPhone, String phone, String maritalStatus, Set<Buyer> buyers,
			Set<Vendor> vendors) {
		this.personId = personId;
		this.fullname = fullname;
		this.identificationNumber = identificationNumber;
		this.individualCode = individualCode;
		this.birthDate = birthDate;
		this.postalCode = postalCode;
		this.federalState = federalState;
		this.city = city;
		this.district = district;
		this.location = location;
		this.country = country;
		this.addressComplement = addressComplement;
		this.cellPhone = cellPhone;
		this.phone = phone;
		this.maritalStatus = maritalStatus;
		this.buyers = buyers;
		this.vendors = vendors;
	}

	@Id
	@Column(name = "PERSON_ID", unique = true, nullable = false)
	public long getPersonId() {
		return this.personId;
	}

	public void setPersonId(long personId) {
		this.personId = personId;
	}

	@Column(name = "FULLNAME", nullable = false)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "IDENTIFICATION_NUMBER", length = 20)
	public String getIdentificationNumber() {
		return this.identificationNumber;
	}

	public void setIdentificationNumber(String identificationNumber) {
		this.identificationNumber = identificationNumber;
	}

	@Column(name = "INDIVIDUAL_CODE", length = 20)
	public String getIndividualCode() {
		return this.individualCode;
	}

	public void setIndividualCode(String individualCode) {
		this.individualCode = individualCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BIRTH_DATE", length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "POSTAL_CODE", length = 20)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "FEDERAL_STATE", length = 45)
	public String getFederalState() {
		return this.federalState;
	}

	public void setFederalState(String federalState) {
		this.federalState = federalState;
	}

	@Column(name = "CITY", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "DISTRICT", length = 45)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "LOCATION", length = 45)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "COUNTRY", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "ADDRESS_COMPLEMENT", length = 45)
	public String getAddressComplement() {
		return this.addressComplement;
	}

	public void setAddressComplement(String addressComplement) {
		this.addressComplement = addressComplement;
	}

	@Column(name = "CELL_PHONE", length = 25)
	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	@Column(name = "PHONE", length = 25)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "MARITAL_STATUS", length = 1)
	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<Buyer> getBuyers() {
		return this.buyers;
	}

	public void setBuyers(Set<Buyer> buyers) {
		this.buyers = buyers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<Vendor> getVendors() {
		return this.vendors;
	}

	public void setVendors(Set<Vendor> vendors) {
		this.vendors = vendors;
	}

}
