package org.jboss.html5.model;
// Generated 25-Sep-2016 11:42:16 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductTag generated by hbm2java
 */
@Entity
@Table(name = "product_tag", catalog = "4fashion")
public class ProductTag implements Serializable {
	private static final long serialVersionUID = -7139230072163581048L;
	
	private long productTagId;
	private Product product;
	private Tag tag;

	public ProductTag() {
	}

	public ProductTag(long productTagId, Product product, Tag tag) {
		this.productTagId = productTagId;
		this.product = product;
		this.tag = tag;
	}

	@Id
	@Column(name = "PRODUCT_TAG_ID", unique = true, nullable = false)
	public long getProductTagId() {
		return this.productTagId;
	}

	public void setProductTagId(long productTagId) {
		this.productTagId = productTagId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_FK", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TAG_FK", nullable = false)
	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

}
