package org.jboss.html5.model;
// Generated 25-Sep-2016 11:42:16 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductManufacturer generated by hbm2java
 */
@Entity
@Table(name = "product_manufacturer", catalog = "4fashion")
public class ProductManufacturer implements Serializable {
	private static final long serialVersionUID = 3257604785865309115L;
	
	private long productManufacturerId;
	private Product product;
	private Manufacturer manufacturer;

	public ProductManufacturer() {
	}

	public ProductManufacturer(long productManufacturerId, Product product, Manufacturer manufacturer) {
		this.productManufacturerId = productManufacturerId;
		this.product = product;
		this.manufacturer = manufacturer;
	}

	@Id
	@Column(name = "PRODUCT_MANUFACTURER_ID", unique = true, nullable = false)
	public long getProductManufacturerId() {
		return this.productManufacturerId;
	}

	public void setProductManufacturerId(long productManufacturerId) {
		this.productManufacturerId = productManufacturerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_FK", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANUFACTURER_FK", nullable = false)
	public Manufacturer getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(Manufacturer manufacturer) {
		this.manufacturer = manufacturer;
	}

}
