package org.jboss.html5.model;
// Generated 25-Sep-2016 11:42:16 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "4fashion")
public class Product implements Serializable {
	private static final long serialVersionUID = -7775170054889900720L;
	
	private long productId;
	private String name;
	private String description;
	private String tags;
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);
	private Set<ProductManufacturer> productManufacturers = new HashSet<ProductManufacturer>(0);
	private Set<ProductTag> productTags = new HashSet<ProductTag>(0);

	public Product() {
	}

	public Product(long productId, String name) {
		this.productId = productId;
		this.name = name;
	}

	public Product(long productId, String name, String description, String tags, Set<OrderItem> orderItems,
			Set<ProductManufacturer> productManufacturers, Set<ProductTag> productTags) {
		this.productId = productId;
		this.name = name;
		this.description = description;
		this.tags = tags;
		this.orderItems = orderItems;
		this.productManufacturers = productManufacturers;
		this.productTags = productTags;
	}

	@Id
	@Column(name = "PRODUCT_ID", unique = true, nullable = false)
	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	@Column(name = "NAME", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TAGS")
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductManufacturer> getProductManufacturers() {
		return this.productManufacturers;
	}

	public void setProductManufacturers(Set<ProductManufacturer> productManufacturers) {
		this.productManufacturers = productManufacturers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductTag> getProductTags() {
		return this.productTags;
	}

	public void setProductTags(Set<ProductTag> productTags) {
		this.productTags = productTags;
	}

}
