package org.jboss.html5.model;
// Generated 25-Sep-2016 11:42:16 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vendor generated by hbm2java
 */
@Entity
@Table(name = "vendor", catalog = "4fashion")
public class Vendor implements Serializable {
	private static final long serialVersionUID = -6574214625252614163L;
	
	private long vendorId;
	private Person person;
	private Integer installmentLimit;
	private Double installmentMinvalue;
	private Double forwardPaymentMinvalue;
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<VendorTag> vendorTags = new HashSet<VendorTag>(0);

	public Vendor() {
	}

	public Vendor(long vendorId, Person person) {
		this.vendorId = vendorId;
		this.person = person;
	}

	public Vendor(long vendorId, Person person, Integer installmentLimit, Double installmentMinvalue,
			Double forwardPaymentMinvalue, Set<Order> orders, Set<VendorTag> vendorTags) {
		this.vendorId = vendorId;
		this.person = person;
		this.installmentLimit = installmentLimit;
		this.installmentMinvalue = installmentMinvalue;
		this.forwardPaymentMinvalue = forwardPaymentMinvalue;
		this.orders = orders;
		this.vendorTags = vendorTags;
	}

	@Id
	@Column(name = "VENDOR_ID", unique = true, nullable = false)
	public long getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(long vendorId) {
		this.vendorId = vendorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSON_FK", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "INSTALLMENT_LIMIT")
	public Integer getInstallmentLimit() {
		return this.installmentLimit;
	}

	public void setInstallmentLimit(Integer installmentLimit) {
		this.installmentLimit = installmentLimit;
	}

	@Column(name = "INSTALLMENT_MINVALUE", precision = 22, scale = 0)
	public Double getInstallmentMinvalue() {
		return this.installmentMinvalue;
	}

	public void setInstallmentMinvalue(Double installmentMinvalue) {
		this.installmentMinvalue = installmentMinvalue;
	}

	@Column(name = "FORWARD_PAYMENT_MINVALUE", precision = 22, scale = 0)
	public Double getForwardPaymentMinvalue() {
		return this.forwardPaymentMinvalue;
	}

	public void setForwardPaymentMinvalue(Double forwardPaymentMinvalue) {
		this.forwardPaymentMinvalue = forwardPaymentMinvalue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendor")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendor")
	public Set<VendorTag> getVendorTags() {
		return this.vendorTags;
	}

	public void setVendorTags(Set<VendorTag> vendorTags) {
		this.vendorTags = vendorTags;
	}

}
